name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
    - uses: actions/setup-python@v3
    - name: Install pygments
      run: pip install pygments
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      env:
        APP_ENV: test
      run: lein test
